application: test-auth
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: test-auth.app

libraries:
- name: webapp2
  version: latest
- name: jinja2                                                                  
  version: latest                                                               

